name: GitHub Profile Summary Cards

on:
  # 每天凌晨 1 点（UTC）执行一次
  schedule:
    - cron: "0 17 * * *"  # 北京时间 1 点 = UTC 17 点
  # 手动触发
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate

    steps:
      - uses: actions/checkout@v4

      - uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          USERNAME: itwanger
          # 你也可以自定义主题，比如 dracula / solarized / github 等
          # 默认是 "default"